name: Extended CI Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci-libs-call:
    uses: ./.github/workflows/ci-libs.yml
    with:
      nexus_url: ${{ vars.NEXUS_URL }}
      docker_nexus_domain: ${{ vars.DOCKER_NEXUS_DOMAIN }}
      nexus_username: admin
      nexus_password: d254a694-f6da-46c2-a875-4171433d7854
